---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  # namespace: <nome-aluno>
type: Opaque
data:
  username: WHgwMTkyMzQ4
  password: RHZpY2VudGluaTEyMzQ=

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  # namespace: <nome-aluno>
spec:
  containers:
  - name: mypod
    image: redis
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: cluster-secrets
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: cluster-secrets
          key: password

#kubectl apply -f sensives.yml