---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

#kubectl apply -f update.yml
#kubectl set image deployments/update-nginx nginx=nginx:1.9.1
#kubectl get pods -l app=nginx -L deployment